import { currentDate } from "../../../helper/currentDate";
import Destination from "./destination";

const credential = localStorage.getItem("token");
const authData = JSON.parse(credential);

export const guideMasterInitialValue = {
  Name: "",
  ServiceType: "Guide",
  Rating: "",
  Email: "",
  Address: "",
  Languages: [],
  Destination: [],
  Phone: "",
  MobileNumber: "",
  WhatsappNumber: "",
  AlternateNumber: "",
  GuideLicense: "",
  LicenseExpiry: "",
  PAN: "",
  GST: "",
  guide_image: "",
  ImageData: "",
  Supplier: "1",
  ContactPerson: "",
  Designation: "",
  Country: "",
  State: "",
  City: "",
  Pincode: "",
  Remark: "",
  Feedback: "",
  Default: "0",
  VaccinationStatus: "1",
  Details: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const guideServiceMasterInititalValue = {
  ServiceType: "Guide",
  Destination: "",
  Guide_Porter_Service: "",
  Default: "No",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  CompanyId: "Debox-01",
};
export const stateInitialValue = {
  id: "",
  Name: "",
  CountryId: "",
  StateCode:"",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const cityInitialValue = {
  id: "",
  CountryId: "",
  StateId: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const sightseeingInitialValue = {
  id: "",
  SightseeingName: "",
  Destination: "",
  Destination: [],
  TransferType: "",
  DefaultQuotation: "1",
  DefaultProposal: "1",
  Description: "",
  InclusionsExclusionsTiming: "",
  ImportantNot: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const businessTypeInitialValue = {
  id: "",
  Name: "",
  SetDefault: 0,
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const languageInitialValue = {
  id: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

//  hotel initial value
export const hotelAddInitialValue = {
  id: "",
  HotelName: "",
  SelfSupplier: "1",
  HotelCountry: 101,
  HotelCity: "",
  Destination: "",
  // DestinationId: "",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  HotelPinCode: "",
  HotelAddress: "",
  HotelGSTN: "",
  HotelType: "",
  HotelCategory: "",
  // HotelCategoryId: "",
  HotelLink: "",
  HotelInfo: "",
  HotelPolicy: "",
  HotelTC: "",
  HotelRoomType: [],
  HotelState: "",
  HotelWeekend: "",
  HotelChain: "",
  HotelAmenities: [],
  Days: "",
  CheckInTime: "11:00",
  CheckOutTime: "12:00",
  PaymentType: "Cash",
  Status: "Active",
  Verified: "",
  InternalNote: "",
  contacts: [],
  ImageName: "",
  ImageData: "",
  Default: "No",
  cutofdayFIT: 0,
  cutofdayGIT: 0,
  TotalNoOfRoom:"",
  TwinRoom:"",
  CompanyId:""
};
export const hotelAddContactInitialValue = {
  Division: "",
  Title: "Mr",
  FirstName: "",
  LastName: "",
  Designation: "",
  CountryCode: "91",
  Phone1: "",
  Phone2: "",
  Phone3: "",
  Email: "",
  SecondaryEmail: "",
};

// room type initial value
export const roomTypeInitialValue = {
  id: "",
  Name: "",
  MaximumOccupancy: "",
  Bedding: "",
  Size: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const additionalRequiremntInitialValue = {
  id: "",
  Name: "",
  DestinationId: [1, 2, 3],
  DestinationName: [],
  TaxSlab: "",
  MarkupApply: 1,
  CurrencyId: "",
  CostType: 1,
  AdultCost: "",
  ChildCost: "",
  InfantCost: "",
  ShowInProposal: 1,
  Details: "",
  Status: 1,
  AddedBy: 1,
};
// amenities initial value
export const amentiesInitialValue = {
  id: "",
  Name: "",
  SetDefault: "0",
  ImageName: "",
  ImageData: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

export const divisionInitialValue = {
  id: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const tourtypeInitialValue = {
  id: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const leadSourceInitialValue = {
  id: "",
  Name: "",
  SetDefault: 0,
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const destinationInitialValue = {
  id: "",
  Name: "",
  CountryId: "",
  StateId: "",
  Description: "",
  images: [],
  WeatherInformation: "",
  AdditionalInformation: "",
  ImageData: "",
  SetDefault: "0",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const seasonTypeInitialValue = {
  id: "",
  //name: "",
  SeasonName: "",
  FromDate: "",
  ToDate: "",
  Default: 0,
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// hotel type initial value
export const hotelTypeInitialValue = {
  id: "",
  Name: "",
  UploadKeyword: "",
  IsHouseBoat: "No",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// hotel meal initial value
export const hotelMealInitialValue = {
  id: "",
  Name: "",
  ShortName: "",
  costsheet: "",
  DisplayOnProposal: "",
  SetDefault: "No",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// wekend initial value
export const weekendInitialValue = {
  id: "",
  Name: "",
  WeekendDays: [],
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// hotel category initial value
export const hotelCategoryInitialValue = {
  id: "",
  Name: "",
  UploadKeyword: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// room master initial value
export const roomMasterInitialValue = {
  id: "",
  Name: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// hotel chain initial value
export const hotelChainInitialValue = {
  id: "",
  Name: "",
  Destination: "",
  HotelWebsite: "",
  ContactType: "",
  ContactName: "",
  ContactDesignation: "",
  ContactCountryCode: "+91",
  Destination: [],
  ContactMobile: "",
  ContactEmail: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// restaurant initial value

export const resturantInitialValue = {
  id: "",
  Name: "",
  Destination: "",
  Address: "",
  Country: "",
  State: "",
  City: "",
  SelfSupplier: "No",
  PinCode: "",
  GSTN: "",
  ContactType: "",
  ContactName: "",
  ContactDesignation: "",
  ImageName: "",
  ImageData: "",
  CountryCode: "+91",
  Phone1: "",
  Phone2: "",
  Phone3: "",
  ContactEmail: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  Default: "No",
};

// restaurant meal plan
export const restaurantMealPlanInitialValue = {
  id: "",
  Name: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// transfer type initial values
export const transferTypeInitialValue = {
  id: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
//vehcile type initial value
export const vehicleTypeInitialValue = {
  id: "",
  Name: "",
  PaxCapacity: "",
  PaxType: "",
  ImageName: "",
  ImageData: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// vehicle initial value
export const vehicleMasterInitialValue = {
  id: "",
  Name: "",
  VehicleType: "",
  Capacity: "",
  VehicleBrand: "",
  ImageName: "",
  ImageData: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const visaTypeInitialValue = {
  id: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const visaCostInitialValue = {
  id: "", // Assuming id is a number, initialize it with 0
  Country: "", // Same for Country if it's a number
  VisaType: "", // Same for VisaType if it's a number
  CountryName: "",
  VisaTypeName: "",
  Status: 1,
  AddedBy: authData?.UserID ? authData.UserID.toString() : "0",
  UpdatedBy: authData?.UserID ? authData.UserID.toString() : "0",
};
export const monumentInitialValue = {
  id: "",
  MonumentName: "",
  Destination: "",
  TransferType: "",
  ClosedOnDays: "",
  DefaultQuotation: "1",
  DefaultProposal: "0",
  Default: "No",
  WeekendDays: [],
  Description: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  falseUnder: "ASI",
  image_name: "",
  image_path: "",
  Images: [],
};
export const trainMasterInitialValue = {
  id: "",
  Name: "",
  ImageName: "",
  ImageData: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// vehicle brand initial value

export const vehicleBrandInitialValue = {
  id: "",
  VehicleTypeId: "",
  VehicleTypeName: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const airlineMasterInitialValue = {
  id: "",
  Name: "",
  ImageName: "",
  ImageData: "",
  Status: "1",
  AddedBy: "1",
  UpdatedBy: "1",
};
// agent master
export const agentMasterInitialValue = {
  id: "",
  BussinessType: "",
  WebsiteUrl: "",
  SalesPerson: "",
  OperationsPerson: "",
  CompanyName: "",
  CompanyType: "",
  Consortia: "",
  ISO: "",
  CompanyPhoneNumber: "",
  CompanyEmailAddress: "",
  Competitor: "",
  MarketType: 1,
  LocalAgent: "No",
  Nationality: 2,
  Country: "",
  Category: "",
  TourType: "",
  PreferredLanguage: 20,
  AgentInfo: "",
  Remarks: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
//supplier master
export const supplierAddInitialValue = {
  id: "",
  Name: "",
  AliasName: "",
  Gst: "",
  Status: "Yes",
  PanInformation: "",
  SupplierService: [],
  Destination: [],
  PaymentTerm: "Cash",
  ConfirmationType: "Manual",
  DefaultDestination: [],
  LocalAgent: "No",
  Agreement: "No",
  Remarks: "",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  AgreementOneImageName: "",
  AgreementOneImageData: "",
  AgreementTwoImageName: "",
  AgreementTwoImageData: "",
};
export const transferMasterInitialValue = {
  TransferName: "",
  Destinations: [],
  TransferType: "",
  Details: "",
  SetDefault: "No",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const transportMasterInitialValue = {
  id: "",
  Name: "",
  DestinationId: [],
  TransferType: "",
  Detail: "",
  TransportType: "",
  Default: "0",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const activityMasterInitialValue = {
  Type: "Activity",
  ServiceName: "",
  UniqueID: "",
  Destination: "",
  Default: "0",
  Supplier: "",
  ClosingDay: [],
  Description: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  cutofdayFIT: "0",
  cutofdayGIT: "0",
};

// Insurance type initial value
export const insuranceTypeInitialValue = {
  id: "",
  InsuranceType: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Insurance Cost initial value
export const insuranceCostInitialValue = {
  id: "",
  InsuranceName: "",
  InsuranceType: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// office
export const addOfficeInitialValue = {
  id: "",
  Name: "Head Office",
  Type: "",
  Fk_partnerid: "",
  Country: "",
  State: "",
  City: "",
  Address: "",
  PinCode: "",
  Pan: "",
  Gstn: "",
  PrimaryAddress: "",
  PlaceOfDeliveryInvoice: "",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// document
export const companyDocumentsInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  DocumentName: "",
  DocumentNumber: "",
  IssueDate: "",
  ExpireDate: "",
  Remarks: "",
  DocumentImageName: "",
  DocumentImageData: "",
  Status: "Yes",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// bank
export const agentBankDetailsInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  BankName: "",
  BankBranch: "",
  AccountNumber: "",
  IfscCode: "",
  PhoneNumber: "",
  EmailId: "",
  SwiftCode: "",
  Address: "",
  CheckToDefault: "Yes",
  BenificiryName: "",
  Status: "Yes",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// contact
export const addContactInitialValue = {
  id: "",
  ParentId: "",
  OfficeName: "Head Office",
  Title: "",
  MetDuring: "",
  FirstName: "",
  LastName: "",
  Division: "",
  Designation: "",
  Newsletter: "Yes",
  CountryCode: "",
  Phone: "",
  MobileNo: "",
  Email: "",
  AlternateEmail: "",
  DateOfBirth: "",
  AnniversaryDate: "",
  SkypeId: "",
  MsnId: "",
  Remarks: "",
  FacebookProfile: "",
  LinkedInProfile: "",
  TwitterProfile: "",
  InstagramProfile: "",
  ImageNameOne: "",
  ImageOneData: "",
  ImageNameTwo: "",
  ImageTwoData: "",
  ImageNameThree: "",
  ImageThreeData: "",
  Status: "Yes",
  Remarks: "",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Passport type initial value
export const passportTypeInitialValue = {
  id: "",
  PassportType: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Currency initial value
export const currencyInitialValue = {
  id: "",
  CountryId: "",
  CountryCode: "",
  Name: "",
  Status: "Active",
  SetDefault: "0",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  ConversionRate: "",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// meeting
export const meetingAddIntitalValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  Fk_Leadsource: "",
  BusinessType: "",
  AgentName: "",
  AgentId: "",
  AgentContactPersonId: "",
  AgentContactPerson: "",
  EmailId: "",
  CountryId: "",
  Destination: "",
  SalesPerson: "",
  MobileNumber: "",
  ContactNumber: "",
  Startdate: "",
  StartTime: "",
  CallDuration: "",
  EndTime: "",
  NextFollowUpdate: "",
  NextFollowUpTime: "",
  ReminderTime: "",
  MeetingOutcome: "",
  Campaign: "",
  MeetingAgenda: "",
  Description: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// call
export const agentAddCallInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  Fk_Leadsource: "",
  BusinessType: "",
  AgentName: "",
  AgentId: "",
  AgentContactPersonId: "",
  AgentContactPerson: "",
  EmailId: "",
  CountryId: "",
  Destination: [],
  SalesPerson: "",
  MobileNumber: "",
  ContactNumber: "",
  Startdate: "",
  StartTime: "",
  CallDuration: "",
  EndTime: "",
  NextFollowUpdate: "",
  NextFollowUpTime: "",
  ReminderTime: "",
  CallType: "",
  Campaign: "",
  CallAgenda: "",
  Description: "",
  CallStatus: "",
  Status: "Yes",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// task
export const addTaskInitialValue = {
  id: "",
  Type: "",
  Fk_partnerid: "",
  Fk_Leadsource: "",
  BusinessType: "",
  AgentName: "",
  AgentId: "",
  AgentContactPersonId: "",
  AgentContactPerson: "",
  EmailId: "",
  CountryId: "",
  Destination: "",
  SalesPerson: "",
  MobileNumber: "",
  ContactNumber: "",
  Startdate: "",
  StartTime: "",
  CallDuration: "",
  EndTime: "",
  NextFollowUpdate: "",
  NextFollowUpTime: "",
  ReminderTime: "",
  Priority: "",
  TaskSubject: "Task Subject",
  Description: "",
  Status: "Yes",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// Tax Initial Value
export const taxInitialValue = {
  id: "",
  ServiceType: "",
  TaxSlabName: "",
  TaxValue: "",
  PriceRangeFrom: "",
  PriceRangeTo: "",
  Currency: "",
  Status: "1",
  SetDefault: "0",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const ferryMasterInitialValue = {
  id: "",
  FerryCompany: 1,
  FerryName: "",
  Capacity: "",
  Status: 1,
  ImageName: "hhhh.png",
  ImageData: "",
  AddedBy: 1,
  UpdatedBy: 1,
};
export const ferrySeatMasterInitialValue = {
  id: "",
  FerrySeat: "",
  Status: 0,
  UpdatedBy: 1,
  AddedBy: 1,
};
// Expense head Value
export const expenceHeadInitialValue = {
  id: "",
  ExpenseHead: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// rate monument
export const monumentRateInitialValue = {
  MonumentId: "",
  DestinationID: "",
  CompanyId: "De-b000000002",
  SupplierId: "",
  NationalityId: "",
  ValidFrom: "",
  ValidTo: "",
  CurrencyId: "1",
  IndianAdultEntFee: "",
  IndianChildEntFee: "",
  ForeignerAdultEntFee: "",
  ForeignerChildEntFee: "",
  TaxSlabId: "",
  Policy: "",
  TAC: "",
  Remarks: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  AddedDate: currentDate(),
  UpdatedDate: currentDate(),
};
// hotel rate
export const hotelRateAddInitialValue = {
  GalaDinner: [{ Name: "", Price: "", Date: "", Meal: "" }],
  BlackoutDates: [
    {
      BlackoutDatesFrom: "",
      BlackoutDatesTo: "",
      BlackoutDatesRemark: "",
    },
  ],
  CompanyId: "",
  HotelId: "",
  HotelUUID: "",
  HotelTypeId: "",
  HotelCategoryId: "",
  HotelChainId:"",
  UserId:"",
  DestinationID: "",
  SupplierId: "",
  ValidFrom: "",
  ValidTo: "",
  MarketTypeId: 1,
  PaxTypeId: "3",
  TarrifeTypeId: "3",
  SeasonTypeID: "",
  SeasonYear: "",
  CurrencyId: 1,
  RoomTypeID: "",
  MealPlanId: "",
  RoomBedType: [],
  MealType: [],
  DayList: [],
  RoomTaxSlabId: "",
  MealSlabId: "",
  MarkupType: "percentage",
  MarkupCost: "",
  Remarks: "",
  WeekendDays: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  AddedDate: currentDate(),
  UpdatedDate: currentDate(),
};
// Expense Type Value
export const expenceTypeInitialValue = {
  id: "",
  ExpenseHead: "",
  ExpenseType: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Country Initial value
export const countryInitialValue = {
  id: "",
  Name: "",
  ShortName: "",
  SetDefault: "1",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  // Monument Packge Initial Value
};
// Monument Packge Initial Value
export const monumentPackageInitialValue = {
  package_name: "",
  destination: "",
  day_type: "Full Day",
  day_time: "",
  monumentId: [],
  image_name: "",
  image: "",
  status: "Active",
  default: "Yes",
  languageDescription: [],
  created_by: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  updated_by: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const hotelAditionalListInitialValue = {
  id: "",
  Name: "",
  Details: "",
  ImageName: "",

  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// guide service initial value
export const guideServiceRateInitialValue = {
  id: "",
  DestinationID: "",
  CompanyId: "De-b000000002",
  SupplierId: "",
  ValidFrom: "",
  ValidTo: "",
  PaxRange: "",
  DayType: "Full Day",
  UniversalCost: "Yes",
  GuideId: "",
  Currency: "1",
  ServiceCost: "",
  LangAllowance: "",
  OtherCost: "",
  GstSlabid: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  AddedDate: currentDate(),
  UpdatedDate: currentDate(),
};
export const guideServiceCostInitial = {
  StartPax: "",
  EndPax: "",
  GuideFullDayFee: "",
  GuideHalfDayFee: "",
  LAFullDayFee: "",
  LAHalfDayFee: "",
  OthersFullDayFee: "",
  OthersHalfDayFee: "",
  Remarks: "",
};

// Market Type Initial value
export const marketTypeInitialValue = {
  id: "",
  Name: "",
  Status: 1,
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  // Monument Packge Initial Value
};

// Passport Cost initial value
export const passportCostInitialValue = {
  id: "",
  PassportName: "",
  PassportType: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Commision initial value
export const commisionCostInitialValue = {
  id: "",
  CommissionName: "",
  CommissionPercentage: "",
  Status: "Active",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Activity rate initial value
export const activityRateInitialValue = {
  id: "",
  ActivityId: "",
  DestinationID: "",
  SupplierId: "",
  Service: "",
  ValidFrom: "",
  ValidTo: "",
  CurrencyId: "",
  ServiceCost: [],
  ChildCost: "",
  PaxRange: "",
  PaxCost: "",
  TotalCost: "",
  TaxSlabId: "",
  Remarks: "",
  CompanyId: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: "1",
  AddedDate: currentDate(),
  UpdatedDate: "0",
};

// transport rate initial value
export const transportRateInitialValue = {
  TransportId: "",
  DestinationID: "",
  SupplierId: "",
  MarketTypeId:"",
  ValidFrom: "",
  ValidTo: "",
  Type: "Package Cost",
  TransferType: [],
  VehicleType: [],
  CompanyId: "",
  CurrencyId: "1",
  TaxSlabId: "",
  NoOfVehicle: "0",
  Remarks: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: "0",
};
export const transportRateVehicleInitialValue = [
  {
    VehicleTypeId: "31",
    VehicleCost: "0",
    ParkingFee: "0",
    RapEntryFee: "0",
    Assistance: "0",
    GrandTotal: "0",
    AdtnlAllowance: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
  {
    VehicleTypeId: "34",
    VehicleCost: "0",
    ParkingFee: "0",
    RapEntryFee: "0",
    GrandTotal: "0",
    Assistance: "0",
    AdtnlAllowance: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
  {
    VehicleTypeId: "25",
    VehicleCost: "0",
    ParkingFee: "0",
    RapEntryFee: "0",
    GrandTotal: "0",
    Assistance: "0",
    AdtnlAllowance: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
  {
    VehicleTypeId: "28",
    VehicleCost: "0",
    ParkingFee: "0",
    GrandTotal: "0",
    RapEntryFee: "0",
    Assistance: "0",
    AdtnlAllowance: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
  {
    VehicleTypeId: "27",
    VehicleCost: "0",
    ParkingFee: "0",
    RapEntryFee: "0",
    Assistance: "0",
    GrandTotal: "0",
    AdtnlAllowance: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
  {
    VehicleTypeId: "27",
    VehicleCost: "0",
    ParkingFee: "0",
    RapEntryFee: "0",
    Assistance: "0",
    AdtnlAllowance: "0",
    GrandTotal: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
  {
    VehicleTypeId: "27",
    VehicleCost: "0",
    ParkingFee: "0",
    RapEntryFee: "0",
    Assistance: "0",
    GrandTotal: "0",
    AdtnlAllowance: "0",
    InterStateToll: "0",
    MiscCost: "0",
  },
];
// transfer rate initial value
export const transferRateAddInitialValue = {
  TransferId: "",
  CompanyId:
    authData?.companyKey != null ? authData?.companyKey?.toString() : "0",
  DestinationID: "",
  SupplierId: "",
  ValidFrom: "",
  ValidTo: "",
  CurrencyId: "",
  VehicleTypeId: "",
  VehicleCost: "",
  ParkingFee: "",
  RapEntryFee: "",
  Assistance: "",
  NoOfVehicle: "",
  AdtnlAllowance: "",
  InterStateToll: "",
  MiscCost: "",
  TaxSlabId: "",
  Remarks: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: "0",
  AddedDate: currentDate(),
  UpdatedDate: "0",
};

// restaurant rate initial value
export const restaurantRateAddInitialValue = {
  RestaurantId: "",
  DestinationID: "",
  CompanyId:
    authData?.companyKey != null ? authData?.companyKey?.toString() : "0",
  SupplierId: "",
  MealTypeId: "",
  Currency: "",
  AdultCost: "",
  ChildCost: "",
  GstSlabId: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: "1",
  AddedDate: currentDate(),
  UpdatedDate: "0",
};

export const trainRateAddInitialValue = {
  TrainId: "",
  CompanyId:
    authData?.companyKey != null ? authData?.companyKey?.toString() : "0",
  SupplierId: "",
  TrainNumber: "",
  JourneyType: "day_journey",
  TrainClassId: "",
  Currency: "",
  AdultCost: "",
  ChildCost: "",
  InfantCost: "",
  Remarks: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: "0",
};

// Payment Type initial value
export const paymentTypeInitialValue = {
  id: "",
  PaymentTypeName: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};

// Saas Code initial value
export const saasCodeInitialValue = {
  id: "",
  ServiceTypeId: "",
  SacCode: "",
  TaxSlabId: "",
  Status: "1",
  SetDefault: "0",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
// Bank Initial Value
export const bankInitialValue = {
  id: "",
  BankName: "",
  currencyid: "",
  purpose: "",
  AccountNumber: "",
  BranchAddress: "",
  UpiId: "",
  AccountType: "",
  BeneficiaryName: "",
  BranchIfsc: "",
  BranchSwiftCode: "",
  ImageName: "",
  ImageData: "",
  ShowHide: "1",
  SetDefault: "0",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const airlineRateAddInitialValue = {
  id: "",
  CompanyId: "Debo000004",
  FlightNumber: "",
  FlightClass: "",
  Currency: "",
  AdultCost: { base_fare: "", airline_tax: "" },
  ChildCost: { base_fare: "", airline_tax: "" },
  InfantCost: { base_fare: "", airline_tax: "" },
  BaggageAllowance: "",
  CancallationPolicy: "",
  Remarks: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  AddedDate: currentDate(),
  UpdatedDate: "0",
};

// operation restriction
export const OperationRestrictionIntialValue = {
  productId: "",
  productName: "",
  restriction_json: {
    serviceId: "",
    serviceName: "",
    destinationId: "",
    destinationName: "",
    FromDate: "",
    ToDate: "",
    Reason: "",
  },
  AddedBy: 1,
  UpdatedBy: 0,
};
export const directClientInitialValue = {
  id: "",
  ContactType: "B2C",
  Nationality: "3",
  Currency: "",
  Title: "",
  FirstName: "",
  MiddleName: "",
  LastName: "",
  Gender: "",
  Contactinfo: [],
  DOB: "",
  AnniversaryDate: "",
  HolidayPreference: [],
  Country: "",
  State: "",
  City: "",
  Pin_Zip: "",
  Address: "",
  Facebook: "",
  Twitter: "",
  LinkedIn: "",
  Instagram: "",
  Skype: "",
  MSN_Id: "",
  Remark1: "",
  Remark2: "",
  Remark3: "",
  SalesPerson: "",
  Status: "1",
  FamilyCode: "",
  FamilyRelation: "",
  MealPreference: "",
  SpecialAssisteance: "",
  SeatPreference: "",
  AccomodationPreference: "",
  MarketType: "1",
  CovidVaccinated: "",
  NewsLetter: "",
  EmergencyContactName: "",
  Relation: "",
  EmergencyContactNumber: "",
  AddedBy: "1",
  UpdatedBy: "0",
};
export const directClientContact = {
  Contact_Type: "",
  CountryCode: "91",
  Mobile: "",
  EmailType: "Work",
  Email: "",
};
export const directClientDocumentation = {
  DocumentType: "",
  DocumentRequired: "",
  DocumentNo: "",
  IssueDate: "",
  ExpiryDate: "",
  IssueCountry: "",
  DocumentTitle: "",
  ImageData: "",
  ImageName: "",
};
// pax slab initial value
export const paxSlabInitialValue = {
  id: "",
  CompanyId: "",
  // UserId: "",
  Min: "0",
  Max: "0",
  DividingFactor: "0",
  // NoOfAdults: "0",
  // NoOfChilds: "0",
  // SingleRoom: "0",
  // DoubleRoom: "0",
  // TripleRoom: "0",
  // TwinRoom: "0",
  // ExtraBed: "0",
  // ChildWithBed: "0",
  Default: "No",
  Type: "FIT",

  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
export const cruisecompanymasterInitialValue = {
  id: "",
  CruiseCompanyName: "",
  Destination: "",
  Country: "",
  State: "",
  City: "",
  PinCode: "",
  Address: "",
  Website: "",
  GST: "",
  SelfSupplier: "",
  Type: "",
  Phone: "",
  Email: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};
//ferry company master initial value
export const ferryCompanyInitialValue = {
  id: "",
  FerryCompanyName: "",
  Destination: "",
  Website: "",
  SelfSupplier: "1",
  Type: "0",
  ContactPers: "",
  Designation: "",
  Phone: "",
  Email: "",
  Status: "1",
  UpdatedBy: "1",
  AddedBy: "1",
};
export const itineraryRequirementInitialValue = {
  id: "",
  FromDestination: "",
  ToDestination: "",
  TransferMode: "",
  Title: "",
  Description: "",
  DrivingDistance: "",
  Status: 1,
  AddedBy: 1,
  UpdatedBy: 0,
};
export const itenararyOverviewInitialValue = {
  id: "",
  OverviewName: "",
  LanguageData: [
    {
      LanguageId: "",
      OverviewName: "",
      Highlights: "",
      ItineraryIntroduction: "",
      ItinerarySummary: "",
      LanguageName: "",
    },
  ],
  Status: 1, // Assuming "1" represents "Active"
  AddedBy: 1,
  UpdatedBy: 1,
};
export const letterMasterInitialValue = {
  id: "",
  Name: "",
  GreetingNote: "",
  WelcomeNote: "",
  Languages: [],
  Status: "1",
  AddedBy: "1",
};
export const CruisenamecompanyInitialValue = {
  id: "",
  CruiseCompany: "",
  CruiseName: "",
  ImageName: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const fitInitialValue = {
  id: "",
  Name: "",
  DestinationId: [],
  DestinationName: "",
  LanguageData: [],
  Inclusion: "",
  Exclusion: "",
  TermsCondition: "",
  Cancelation: "",
  ServiceUpgradation: "",
  OptionalTour: "",
  PaymentPolicy: "",
  Remarks: "",
  SetDefault: "Yes",
  Status: "Active",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const gitInitialValue = {
  id: "",
  Type: "",
  Name: "",
  ServiceUpgradation: "",
  OptionalTour: "",
  Destination: [],
  LanguageData: [],
  SetDefault: "0",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const fleetInitialValue = {
  id: "",
  Parts: "",
  EngineNumber: "",
  PolicyNumber: "",
  SeatingCapacity: "",
  DueDate: "",
  PremiumAmount: "",
  CategoryVehicleGroup: "",
  CoverAmount: "",
  TaxEfficiency: "",
  ExpiryDate: "",
  RegistrationDate: "",
  VehicleType: "",
  Image: "",
  Vehicle: "",
  RegistrationNumber: "",
  Colour: "",
  FuelType: "",
  AssignedDriver: "",
  Insurance: "",
  IssueDate: "",
  Permits: "",
  PollutionPermitsExpiry: "",
  Status: "Actiive",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const driverMasterInitialValue = {
  id: "",
  Country: "",
  DriverName: "",
  MobileNumber: "",
  AlternateMobileNo: "",
  WhatsappNumber: "",
  LicenseNumber: "",
  BirthDate: "",
  LicenseName: "",
  PassportNumber: "",
  Address: "",
  ValidUpto: "",
  ImageName: "",
  Status: "Active",
  AddedBy: "",
  UpdatedBy: "",
};
export const CabintypeInitialValue = {
  id: "",
  CruiseName: "",
  CabinType: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const CabincategoryInitialValue = {
  id: "",
  Name: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const CruisemasterInitialValue = {
  id: "",
  CruisePackageName: "",
  Destination: "",
  RunningDays: "",
  ArrivalTime: "",
  DepartureTime: "",
  Status: "1",
  AddedBy: 1,
  UpdatedBy: 0,
};
export const excelFormatAddInitialValue = {
  id: "",
  ServiceType: "",
  Title: "",
  TemplateName: "",
};
export const VisasummaryInitialValue = {
  Id: "",
  Country: "",
  CountryId: "",
  Description: "",
};
export const distanceInitialValue = {
  Id: "",
  FromDestination: "",
  ToDestination: [],
};
export const destinationimageInitialValue = {
  id: "",
  ServiceId: "",
  ServiceType: "",
  images: [],
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};


export const addEditOfficeInitialValue = {
  id: "",
  CompanyId: "",
  OfficeName: "",
  Country: 101,
  State: "",
  City: "",
  Address: "",
  ContacctPersonName: "",
  Email: "",
  CountryCode: "",
  Phone: "",
  Mobile: "",
  GstNo: "",
  Currency: "",
  Status: "1",
  AddedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
  UpdatedBy: authData?.UserID != null ? authData?.UserID?.toString() : "0",
};
