const queryAddInitialValue = {
  ClientType: 1,
  TAT: "",
  LeadSource: "",
  MealPlan: "3",
  Consortia: "1",
  ClientName: "",
  CurrencyId: "",
  ConversionRate: "",
  Language: "18",
  // ISO: "",
  Budget: "",
  QueryType: [],
  ServiceDetail: {
    ServiceId: "",
    BusinessTypeId: "",
  },
  ContactInfo: {
    ContactId: "",
  },
  PaxInfo: {
    PaxType: "1",
    TotalPax: "",
    Adult: 0,
    Child: 0,
    Infant: 0,
  },
  TravelDateInfo: {
    ScheduleType: "Day Wise",
    SeasonType: "",
    SeasonYear: new Date().getFullYear(),
    FromDate: new Date().toISOString().split("T")[0],
    FromDateDateWise: new Date().toISOString().split("T")[0],
    ToDate: "",
    TotalNights: "",
    TravelData: "",
  },
  Prefrences: "",
  Description: "",
  TravelType: "Inbound",
  ValueAddedServices: {},
  Hotel: {
    HotelCategory: "0",
    RoomInfo: "",
  },
};

const preferencesInitialValue = {
  TourType: "",
  LeadReferencedId: "",
  VehiclePreference: "",
  HotelType: "",
  Priority: "",
  SalesPerson: "",
  OperationPerson: "",
  ContractingPerson: "",
  HotelPreference: "",
};
const insuranceInitial = {
  InsuranceType: "",
  InsuranceFromDate: "",
  InsuranceToDate: "",
  TravelingCountry: "",
};
const addPereferenceInitialValue = {
  CompanyId: "",
  UserId: "",
  SetPreference: "High",
  Preview: "",
  TravelInfo: "",
  Email: "",
  VehiclePreferenceId: "",
  Preferences: {
    BusinessTypeId: "",
    QueryTypeId: "",
    PaxTypeId: "",
    HotelTypeId: "",
    HotelCategoryId: "",
    Assignment: {
      SalesPersonId: "",
      ContractingPersonId: "",
    },
    SalesPerson: {
      IsoId: "",
      ConsortiaId: "",
    },
  },
  Status: 1,
  AddedBy: 1,
  UpdatedBy: 1,
};
export const reminderIntialValue = {
  QueryID: "",
  StatusId: "",
  Type: "",
  RemarkJson: {
    Remark: "",
    NoteTypeName: "",
    ReminderDate: "",
    ReminderTime: "",
    StatusId: "",
  },
};

const ManaulInvoiceIntialValue = {
  // id: "",
  QueryId: "",
  QuotationNo: "",
  Type: "",
  TourId: "",
  ReferenceId: "",
  AddedBy: "",
  UpdatedBy: "",
  InvoiceDetails: {
    InvoiceType: "",
    FormatType: "",
    CostType: "",
    GstType: "",
    Tcs: "",
    TourAmount: "",
    CompanyLogo: "",
    CompanyName: "",
    CompanyAddress: "",
    CompanyContact: "",
    CompanyEmail: "",
    CompanyWebsite: "",
    CompanyPan: "",
    CompanyCIN: "",
    BillToCompanyName: "",
    BillToCompanyAddress: "",
    BillToCompanyContact: "",
    BillToCompanyEmail: "",
    BillToCompanyWebsite: "",
    BillToCompanyPan: "",
    BillToCompanyCIN: "",
    InvoiceNo: "",
    InvoiceDate: "",
    ReferenceNo: "",
    DueDate: "",
    ToutDate: "",
    FileNo: "",
    Currency: "",
    GuestNameorReceiptName: "",
    PlaceofDeliveryId: "",
    PlaceofDeliveryName: "",
    Particulars: [],
    TotalTourCost: "",
    Cgst: "",
    Sgst: "",
    GrantTotal: "",
    BankDetails: [],
    TermsandCondition: "",
    PaymentDesc: "",
  },
};

export {
  queryAddInitialValue,
  preferencesInitialValue,
  insuranceInitial,
  addPereferenceInitialValue,
  ManaulInvoiceIntialValue,
};
