export const hotelItineraryValue = {
  id: "",
  QuatationNo: "",
  DayType: "",
  DayNo: "",
  DayUniqueId: "",
  Escort: 1,
  ServiceMainType: "No",
  Destination: "",
  Supplier: "",
  Hike: "",
  Date: "",
  DestinationUniqueId: "",
  HotelCategory: "",
  RoomCategory: "",
  MealPlan: "",
  OverNight: "",
  FromDay: "",
  ToDay: "",
  ServiceId: "",
  ItemFromDate: "",
  ItemFromTime: "",
  ItemToDate: "",
  InfantCost: "",
  ItemToTime: "",
  PaxSlab: "",
  ServiceMainType: "No",
  RateUniqueId: "",
  RoomBedType: [],
  MealType: [],
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itineraryMonumentInitialValue = {
  id: "",
  QuatationNo: "",
  DayType: "",
  Escort: 1,
  DayNo: "",
  Sector: "",
  Hike: "",
  MonumentDayType: "",
  MonumentTime: "None",
  DayUniqueId: "",
  SupplierId: "",
  Destination: "",
  Date: "",
  Leasure: "",
  Include: "",
  DestinationUniqueId: "",
  ServiceIdMonument: [],
  FromDay: "",
  ToDay: "",
  ServiceId: "",
  ItemFromDate: "",
  ItemFromTime: "",
  ItemToDate: "",
  ItemToTime: "",
  ServiceMainType: "No",
  ItemUnitCost: {
    Adult: "",
    Child: "",
    FAdult: "",
    FChild: "",
  },
  RateUniqueId: "",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itineraryGuideIntialValue = {
  id: "",
  QuatationNo: "",
  DayNo: "",
  Hike: "",
  Type: "",
  Sector: "",
  DayType: "",
  Escort: "1",
  Language: "",
  LanguageAllowance: 0,
  ServiceMainType: "No",
  GuideFee: 0,
  Suppliment:"No",
  Supplier: "",
  OtherCost: 0,
  Destination: "",
  DayUniqueId: "",
  FromDay: "",
  ToDay: "",
  ServiceId: "",
  ItemFromDate: "",
  ItemFromTime: "",
  ItemToDate: "",
  ItemToTime: "",
  PaxSlab: "4",
  RateUniqueId: "",
  ServiceMainType: "No",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  TotalCostingMealPlan: [
    {
        MealType: "",
        ServiceCost: "",
        Markupvalue: "",
        MarkupTotalValue: "",
        TotalServiceCost: ""

    }
  ]

};
export const itineraryTransportInitialValue = {
  id: "",
  QuatationNo: "",
  DayType: "",
  DayNo: "",
  DayUniqueId: "",
  Hike: "",
  Date: "",
  DestinationUniqueId: "",
  ServiceMainType: "No",
  Escort: 1,
  FromDay: "",
  ToDay: "",
  FromDestination: "",
  ToDestination: "",
  TransferType: "",
  Mode: "",
  MainVehicleTypeId: "",
  Supplier: "",
  TransportDetails: "",
  Remarks: "",
  // Assitance:"",
  c: [],
  CostType: "Package Cost",
  NoOfVehicle: "",
  Cost: "",
  AlternateVehicle: "",
  AlternateVehicleCost: "",
  NoOfDay: "",
  ServiceId: "",
  ItemFromDate: "",
  ItemFromTime: "",
  ItemToDate: "",
  ItemToTime: "",
  ServiceMainType: "No",
  RateUniqueId: "",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itineraryActivityInitialValue = {
  id: "",
  QuatationNo: "",
  DayType: "",
  DayNo: "",
  Hike: "",
  Date: "",
  Escort: 1,
  Destination: "",
  ActivityTime: "None",
  Supplier: "",
  DestinationUniqueId: "",
  DayUniqueId: "",
  ServiceId: "",
  Description: "",
  PaxRange: "",
  Cost: "",
  NoOfActivity: 1,
  ServiceType: "Activity",
  ItemFromDate: "",
  ItemFromTime: "",
  ItemToDate: "",
  ItemToTime: "",
  RateUniqueId: "",
  ServiceMainType: "No",
  Supplement: "No",
  Package: "No",
  Highlights: "No",
  BeforeSS: "No",
  Escort: "No",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itinerariesTrainInitialValue = {
  id: "",
  QuatationNo: "",
  DayNo: "",
  Type: "",
  DayType: "",
  Hike: "",
  Sector: "",
  TypeName: "",
  ServiceCharges: "",
  HandlingCharges: "",
  GuideCharges: "",
  ServiceMainType: "No",
  DepartureTime: "",
  SupplierId: "",
  Escort: 1,
  Date: "",
  DestinationUniqueId: "",
  AdultCost: "",
  ChildCost: "",
  ArrivalTime: "",
  Remarks: "",
  TrainNumber: "",
  TrainClass: "",
  FromDestination: "",
  ToDestination: "",
  DayUniqueId: "",
  ServiceId: "",
  ItemFromDate: "",
  ItemToDate: "",
  RateUniqueId: "",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itineraryFlightInitialValue = {
  id: "",
  QuatationNo: "",
  DayNo: "",
  ServiceId: "",
  Type: "1",
  DayType: "",
  Hike: "",
  TypeName: "",
  SupplierId: "",
  Escort: 1,
  ServiceCharges: "",
  HandlingCharges: "",
  GuideCharges: "",
  ServiceMainType: "No",
  DepartureTime: "",
  Supplier: "",
  ArrivalTime: "",
  Remarks: "",
  FlightNumber: "",
  FlightClass: "",
  FromDestination: "",
  ToDestination: "",
  AdultCost: "",
  ChildCost: "",
  InfantCost: "",
  ItemFromDate: "",
  ItemFromTime: "",
  ItemToDate: "",
  ItemToTime: "",
  RateUniqueId: "",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itineraryAdditionalInitialValue = {
  id: "",
  QuatationNo: "",
  DayNo: "",
  DayUniqueId: "",
  DayType: "",
  ServiceMainType: "No",
  Suppliment:"No",
  Hike: "",
  Sector: "",
  ServiceId: "",
  CostType: "Per Person",
  Destination: "",
  SupplierId: "",
  DestinationUniqueId: "",
  Date: "",
  PaxUpTo: "",
  AdultCost: "",
  ChildCost: "",
  ItemFromDate: "",
  ItemToDate: "",
  RateUniqueId: "",
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const itineraryRestaurantInitialValue = {
  id: "",
  QuatationNo: "",
  DayNo: "",
  DayType: "",
  ServiceMainType: "No",
  Sector: "",
  Hike: "",
  DayUniqueId: "",
  ServiceId: "",
  ItemFromDate: "",
  Escort: 1,
  ItemToDate: "",
  SupplierId: "",
  RateUniqueId: "",
  DestinationUniqueId: "",
  Date: "",
  Destination: "",
  Supplier: "",
  AdultCost: "",
  ChildCost: "",
  StartTime: "",
  EndTime: "",
  // RestaurantMealType: [
  //   {
  //     id: "",
  //     MealTypeName: "",
  //     ServiceCost: "",
  //     Markupvalue: "",
  //     MarkupTotalValue: "",
  //     TotalServiceCost: "",
  //   },
  //   {
  //     id: "",
  //     MealTypeName: "",
  //     ServiceCost: "",
  //     Markupvalue: "",
  //     MarkupTotalValue: "",
  //     TotalServiceCost: "",
  //   },
  // ],
  MealPlan: [
    {
      MealType: "",
      // HotelId: "",
      // HotelName: "",
      // RestaurantId: "",
      // RestaurantName: "",
      Supplement: "",
      ServiceID:"",
      ServiceType:"",
      Amount: "",
    },
    {
      MealType: "",
      ServiceID:"",
      ServiceType:"",
      // HotelId: "",
      // HotelName: "",
      // RestaurantId: "",
      // RestaurantName: "",
      Supplement: "",
      Amount: "",
    },
    {
      MealType: "",
      ServiceID:"",
      ServiceType:"",
      Supplement: "",
      Amount: "",
    },
  ],
  PaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
  ForiegnerPaxInfo: {
    Adults: "",
    Child: "",
    Infant: "",
    Escort: "",
  },
};
export const restaurantMealInitial = [
  {
    MealType: "Breakfast",
    ServiceID:"",
    ServiceType:"",
    Supplement: "No",
    RestaurantId:" ",
    Amount: "",
    IsMealType: "NO"
  },
  {
    MealType: "Lunch",
    ServiceID:"",
    ServiceType:"",
    Supplement: "No",
    RestaurantId:"",
    Amount: "",
    IsMealType: "No"
  },
  {
    MealType: "Dinner",
    ServiceID:"",
    ServiceType:"",
    Supplement: "No",
    RestaurantId:"",
    Amount: "",
    IsMealType: "NO"
  },
];
export const localEscortChargesInitialValue = {
  QueryId: "",
  QuotationNumber: "",
  ExcortType: "",
  FromDay: "1",
  ToDay: "1",
  Particular: "",
  AmountPerDay: "",
  TotalDays: "",
  TotalAmount: "",
  Remarks: "",
  LanguageID: "",
};
export const paxSlabInitialValue = {
  QueryId: "",
  QuotationNumber: "",
  ExcortType: "",
  Pax: "",
  Escort: "",
  Factor: "",
  Single: "",
  Double: "",
  Hotel: "",
  Fee: "",
  Meal: "",
  Activity: "",
  Additional: "",
  Train: "",
  Air: "",
  TotalPerPerson: "",
};
export const quotationIntialValue = {
  QueryId: "",
  QuotationNumber: "",
  OverviewId: "",
  FitId: "",
  HotelId: "",
  LanguageId: "",
  DestinationId: "",
  CurrencyId: "",
  CustomerCost: {
    CustomerCostDetails: {
      QuotationCost: "0",
      Paidvalue: "0",
    },
    CustomerPaymentDetails: [
      {
        PaymentMethod: "Credit Card",
        PaymentValue: "0",
        PaymnetCurrency: "USD",
      },
    ],
  },
  OverviewIncExcTc: {
    TourHeighligts: "",
    Overview: "",
    ItineraryIntroduction: "",
    ItinerarySummary: "",
  },
  FitIncExc: {
    Inclusion: "",
    Exclusion: "",
    TermsNCondition: "",
    CancellationPolicy: "",
    "Payment Policy": "",
    Remarks: "",
  },
  Markup: {
    MarkupType: "Universal",
    Data: [],
  },
  Commision: {
    IsoCommision: "",
    ClientCommision: "",
  },
  SupplimentSelection: {
    FlightCost: "",
    TourEscort: "",
  },
  MealSuppliment: [
    {
      Rate: [
        {
          Name: "Breakfast",
          Include: "Yes",
          Price: 0.0,
        },
        {
          Name: "Lunch",
          Include: "Yes",
          Price: 0.0,
        },
        {
          Name: "Dinner",
          Include: "Yes",
          Price: 0.0,
        },
      ],
    },
  ],
  OthersInfo: {
    GstType: "",
    Gst: "",
    TCS: "",
    DiscountType: "",
    Discount: "",
    SrsandTrr: "",
    TermsNCondition: "",
    CurrencyId: "",
    CurrencyName: "",
    ROE: "",
  },
};

// pax slab initial value
export const paxSlabTableInitialValue = {
  QueryId: "",
  QuotationNumber: "",
  CompanyId: "",
  UserId: "",
  Min: "",
  Max: "",
  DividingFactor: "",
  NoOfAdults: "",
  NoOfChilds: "",
  SingleRoom: "",
  DoubleRoom: "",
  TripleRoom: "",
  TwinRoom: "",
  ExtraBed: "",
  ChildWithBed: "",
  CnBed: "",
  Status: "0",
  AddedBy: "",
};

export const clientVoucherInitialValue = {
  UniqueId: "",
  QueryId: "",
  Type: "Client",
  QuotationNo: "",
  CompanyId: "",
  CompanyName: "",
  Website: "",
  CompanyLogo: "",
  ServiceId: "",
  ServiceName: "",
  ServiceType: "",
  Address: "",
  ContactPersonaName: "",
  Email: "",
  Phone: "",
  TourId: "",
  VoucherNo: "",
  VoucherDate: "",
  TotalPax: "",
  ConfirmationNo: "",
  PaxName: [],
  Date: "",
  SupplierId: "",
  Suppliername: "",
  Destinationid: "",
  DestinationName: "",
  ArrivalOn: "",
  DepartureOn: "",
  Fromdestination: "",
  ToDestination: "",
  ArrivalBy: "",
  DepartureBy: "",
  ArrivalAt: "",
  DepartureAt: "",
  Note: "Enter Notes",
  BillingInstructions: "Enter Billing Instructions",
};
export const supplierVoucherInitialValue = {
  UniqueId: "",
  QueryId: "",
  Type: "Supplier",
  QuotationNo: "",
  CompanyId: "",
  CompanyName: "",
  Website: "",
  CompanyLogo: "",
  ServiceId: "",
  ServiceName: "",
  ServiceType: "",
  Address: "",
  ContactPersonaName: "",
  Email: "",
  Phone: "",
  TourId: "",
  VoucherNo: "",
  VoucherDate: "",
  TotalPax: "",
  ConfirmationNo: "",
  PaxName: [],
  Date: "",
  SupplierId: "",
  Suppliername: "",
  Destinationid: "",
  DestinationName: "",
  ArrivalOn: "",
  DepartureOn: "",
  Fromdestination: "",
  ToDestination: "",
  ArrivalBy: "",
  DepartureBy: "",
  ArrivalAt: "",
  DepartureAt: "",
  Note: "Enter Notes",
  BillingInstructions: "Enter Billing Instructions",
};
