export const restaurantPayload = async () => {
  const payload = {
    id: queryData?.id,
    QuatationNo: quotationData?.QuotationNumber,
    DayNo: dayData?.Day,
    DayType: "Main",
    ServiceMainType: "No",
    Sector: "Delhi",
    Hike: "",
    DayUniqueId: dayKey,
    ServiceId: serviceId,
    ItemFromDate: "",
    Escort: 1,
    ItemToDate: "",
    SupplierId: "",
    RateUniqueId: "",
    DestinationUniqueId: "",
    Date: "",
    Destination: dayData?.DestinationId,
    Supplier: supplierByDestination.id,
    AdultCost: "",
    ChildCost: "",
    StartTime: "",
    EndTime: "",
    MealPlan: mealPackageData,
    PaxInfo: {
      Adults: quotationData?.Pax?.AdultCount || "",
      Child: quotationData?.Pax?.ChildCount || "",
      Escort: "",
    },
    ForiegnerPaxInfo: {
      Adults: "",
      Child: "",
      Infant: "",
      Escort: "",
    },
    TotalCostingMealPlan: [],
  };
};
